### ISSUE TITLE
Wrong default port number

### ISSUE THREAD

**Issue by photonlili** [quakelive-server-standards/server-standards#17]
https://github.com/quakelive-server-standards/server-standards/blob/79b8c3f3d46c380e1c274b2b91c38e3e240d2fab/docker/ql-server/Dockerfile#L42

**Comment by NaincyKumariKnoldus** [comment]
Hey @photonlili Can I do this?

**Comment by gastmeier** [comment]
Fixed with commit 26c42e71cb6bc8f57e363765123e70ebc53ef322. Also rebuild and reuploaded Docker images to Docker Hub.
